### ISSUE TITLE
iOS 11+ support

### ISSUE THREAD

**Issue by akirmse** [roznet/FitFileParser#1]
Thank you for this library; it has saved me a lot of time!

However, my app currently supports iOS 11+, while this library requires iOS 13, and I would like not to lose iOS 11 and 12 users.  Would it be easy to lower the requirement?

**Comment by roznet** [comment]
I just updated it for iOS 11, let me know if it works for you

**Comment by akirmse** [comment]
That did the trick.  Thanks!
