### ISSUE TITLE
Issue with rear_gear_change event

### ISSUE THREAD

**Issue by tevendale** [roznet/FitFileParser#3]
I'm trying to decode the '*rear_gear_change*' event.

If I use .generic decoding, then I get a string value something like '*FitField(withName: fit_type_254_704719362)*' for the key 'gear_change_data'. That's fine, and what I'd expect. given the description of generic decoding in the readme.

If I use .fast decoding, however, I'd expect to get a uint32 value for the key '*rear_gear_change*', but I'm not getting that. I understand that what's decoded is determined by the 'profile.xlsx' file, but, in the current version, there's a '1' in the 'Example' column for '*gear_change_data*' in the Event message, so I'd expect to get this data.

I quite appreciate I'm probably doing something wrong here, but any pointers would be appreciated.

**Comment by roznet** [comment]
Hi,
would it be possible to share a fit file with the rear_gear_change data so I can test it?
thanks!

**Comment by tevendale** [comment]
Hi,
Here's the file I've been using for testing.
Thanks
[gearstest.fit.zip](https://github.com/roznet/FitFileParser/files/8302723/gearstest.fit.zip)
.

**Comment by roznet** [comment]
Ok, I had a look, it is because the gear_change_data is a "component" field, which means one number has 32 bits that need to be subdivided into 4 other fields and FitFileParser does not support this yet. I have started working on it.

**Comment by tevendale** [comment]
Thanks - here's the code I used to code the value, if it's any help:
```
    func gearsFromEventData(data: UInt32) -> Array<Any> {
        var bigEndian = data.bigEndian
        let count = MemoryLayout<UInt32>.size
        let bytePtr = withUnsafePointer(to: &bigEndian) {
            $0.withMemoryRebound(to: UInt8.self, capacity: count) {
                UnsafeBufferPointer(start: $0, count: count)
            }
        }
        let byteArray = Array(bytePtr)
        return byteArray
    }

```
I'm pretty sure decoding this did work in an old version of this library - I'm revisiting an old project that used it.

Thanks for your help.

**Comment by roznet** [comment]
it should work now. the library wasn't processing components at all, it does now for .fast parsing.

**Comment by tevendale** [comment]
That's great, thanks.
